version: '3.9'

services:
  user-service:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: user-docker
    container_name: user-container
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: database
      DB_USERNAME: user
      DB_PASSWORD: secret
    # volumes:
    #   - ./:/var/www/user-db

  db:
    image: postgres:alpine3.18
    container_name: postgres-user
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database